name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Client Code
        run: docker run --rm -v ${PWD}:/client openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g go -o /client/generated/go

      - name: Git Commit
        run: |
          git config --local user.name 'Build-Machine'
          git config --local user.email 'wwww3426@naver.com'
          git add *
          git commit -m 'Add Clinet Generated Code'
          git push https://${{ github.actor }}:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git origin go --follow-tags --force